### ISSUE TITLE
rangeBar x-axis tooltips don't display with v3.36.0

### ISSUE THREAD

**Issue by andrussuitsu** [apexcharts/apexcharts.js#3453]
X-axis tooltips are not displayed for rangeBar with apexcharts v3.36.0 but work correctly with v 3.35.5.

### Steps to Reproduce

Please have a look at codepen https://codepen.io/andrussuitsu/pen/wvXBoBr
I have configured it to use v3.35.5 library and it works

The same code is used here: https://codepen.io/andrussuitsu/pen/qBKEqzr
It has been configured to use v3.36.0 and the tooltips are not displayed

### Expected Behavior

Display tooltips when I hover over the range.

### Actual Behavior

Tooltips are no longer displayed when I use the latest apexcharts version (v3.36.0 as of now).

### Reproduction Link

https://codepen.io/andrussuitsu/pen/wvXBoBr -- all is good
https://codepen.io/andrussuitsu/pen/qBKEqzr -- tooltips not displayed

**Comment by junedchhipa** [comment]
Fixed in v.3.36.1

**Comment by jayshah1232** [comment]
I'm still facing this issue even on 3.36.1. The Timeline example page available on the ApexCharts website still shows no tooltip and throws the "opts.ctx.rangeBar.getTooltipValues is not a function" error to the console.

![image](https://user-images.githubusercontent.com/27381013/200000970-db975078-6c3e-4153-99d0-8e0f2abbd0a8.png)
![image](https://user-images.githubusercontent.com/27381013/200001119-9dfd2993-771f-4044-a1b4-9834eda96958.png)
