### ISSUE TITLE
Types: Exports and export assignments are not permitted in module augmentations.

### ISSUE THREAD

**Issue by Dohxis** [apexcharts/apexcharts.js#577]
Been trying to install and use Apexcharts inside a Typescript project, but keep getting this weird error. 

```
[ ERROR ]  TypeScript: node_modules/apexcharts/types/apexcharts.d.ts:956:1
           Exports and export assignments are not permitted in module augmentations.

    L955:  declare module 'apexcharts' {
    L956:  	export = ApexCharts;
    L957:  }
```
I was trying to fix this, and I found a way to get away from this error, I am just not sure if this is a right [fix](https://www.diffchecker.com/0VT6lBUQ).

**Comment by outofmemoryagain** [comment]
I just updated my version and I'm seeing the same error.  I will have to downgrade to continue.

**Comment by junedchhipa** [comment]
Did you upgraded to 3.6.10 to see this error?

**Comment by lesharris** [comment]
@junedchhipa FWIW, I got this issue after an upgrade to 3.6.10 in a typescript project as well. Moved back to 3.6.9 and no issue.

**Comment by Dohxis** [comment]
Can confirm, 3.6.9 has no issue.

**Comment by junedchhipa** [comment]
I have tried a possible fix [here](https://github.com/apexcharts/apexcharts.js/commit/977f5a55feb9ab1b1a95bf71049ea4f17185dde8)

Can anyone test and confirm if the fix works? So, I will push a new patch release.

**Comment by niemyjski** [comment]
I'm also hitting this with typescript 3.2.4

**Comment by mikaelkaron** [comment]
I can confirm that the fix works for me

**Comment by MeStrak** [comment]
Worked for me too, thanks! Although in the end I had too many other ts errors and I needed my build to work so I had to temporarily change tsconfig.json compilerOptions strict from true to false:"compilerOptions": {
    "strict": **false**,

**Comment by diegovallarta** [comment]
It works for me too, thanks!

**Comment by junedchhipa** [comment]
Released 3.6.11

**Comment by niemyjski** [comment]
@junedchhipa Guys.... You are a library and need to export your types..... Make it fully public.

```
src/app/components/apexchart/apexchart.component.ts(2,35): error TS2305: Module '"apexcharts"' has no exported member 'ApexAxisChartSeries'.
src/app/components/events/events.component.ts(117,43): error TS2345: Argument of type 'true' is not assignable to parameter of type 'EntityChanged'.```

**Comment by iclemens** [comment]
Hey @junedchhipa, I think your fix is too simplistic as importing types like ApexAxisChartSeries is no longer possible.

A (very simplistic) use case for importing these types is:

```
import { ApexAxisChartSeries } from 'apexcharts';
const series: ApexAxisChartSeries = [{ name: "Name", data: [1, 2, 3, 4]}];
```

Exporting at least ApexAxisChartSeries would also allow you to properly type the series property here:
https://github.com/apexcharts/react-apexcharts/blob/master/types/react-apexcharts.d.ts
instead of just using Array<any>.
