### ISSUE TITLE
Apexcharts not working with MithrilJS since 2.2.0 version

### ISSUE THREAD

**Issue by czopas** [apexcharts/apexcharts.js#398]
I have a problem with integration Apexcharts with MithrilJS. Everything works well on version 2.2.0, but in newer versions I always have error like:

`Uncaught TypeError: this.charts.render is not a function`

The same behavior produces render() and updateOptions() functions.

Short code:
```
import m from 'mithril';
import ApexCharts from 'apexcharts';

export default class Chart {
  constructor() {
    this.chart = null;
  }

  oninit(vnode) {
    // load chart data
  }

  oncreate() {
    const optionsTemperature = {};
    this.chart = new ApexCharts(
      document.querySelector('#chart-raw-data'),
      optionsTemperature
    );
    this.chart.render();
  }

  view() {
    return (
      <div id='chart-raw-data' />
    );
  }
}
```

Could anyone more advanced help?

Thanks in advance.

**Comment by junedchhipa** [comment]
Can you confirm if ApexCharts stopped working exactly after v2.2.0?
Does it work in 2.6.0?

**Comment by czopas** [comment]
Yes, you are right. On v2.6.0 everything works (except updateOptions()) but on v2.7.0-0 I have the same error message.

I can use v2.6.0 but let me know why updateOptions() not return Promise:
```
Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
```
and not changing options after use.

**Comment by junedchhipa** [comment]
`updateOptions` will not return the Promise if there is an exception. 
Any chance this bug can be reproduced on codesandbox environment? So, I can take a closer look at what exactly is raising the exception.

**Comment by czopas** [comment]
Please look:
[https://codesandbox.io/s/v6zrm8kyw5](url)

After that use link in codesandbox:
[https://v6zrm8kyw5.codesandbox.io/#!/charts](url)

After refresh, onupdate() appear in console, but updateOptions() do not change yaxis annotation.

**Comment by junedchhipa** [comment]
Glad you figured it out yourself, I missed it when I checked the code.
Closing it.
