### ISSUE TITLE
DataURI not working after version 3.16.1

### ISSUE THREAD

**Issue by bluetechdev** [apexcharts/apexcharts.js#1380]
var dataURL = chart.dataURI().then((uri) => {
            var doc = new jsPDF();
            doc.text(20, 30, "Hello!");
            doc.addImage(uri, 'PNG', 5, 0, 200, 110);
            doc.save("rapport.pdf");
        })

Is not working anymore after version 3.15.5 I really need this to generate pdf's with jspdf.  I get the following error:
Uncaught (in promise) TypeError: imageData.charCodeAt is not a function
    at Object.jsPDFAPI.getImageFileTypeByImageData (jspdf.debug.js:6817)
    at Object.jsPDFAPI.addImage (jspdf.debug.js:7580)
    at graphoptions.php:155
It does however work with apex charts v3.15.5.

**Comment by junedchhipa** [comment]
Sorry, the latest version of apexcharts as of today is 3.16.1
Are you sure you are checking the correct version?

**Comment by bluetechdev** [comment]
> Sorry, the latest version of apexcharts as of today is 3.16.1
> Are you sure you are checking the correct version?

I tried every version after 13.5.5 none of them work. What I mean is , it got broken after version 13.5.5

**Comment by bluetechdev** [comment]
> Sorry, the latest version of apexcharts as of today is 3.16.1
> Are you sure you are checking the correct version?

I meant 3.15.5 not 13.15.5

**Comment by junedchhipa** [comment]
You're right.
The parameters in the function were changed a bit.

Please try this

```javascript
var chart = new ApexCharts(el, options);
var dataURL = chart.dataURI().then(({ imgURI, blob }) => {
  var pdf = new jsPDF();
  pdf.addImage(imgURI, 'PNG', 0, 0);
  pdf.save("download.pdf");
})
```

Sorry for the confusion, the change was not documented. I have updated the docs now.
