### ISSUE TITLE
Bar chart disappears  ( timeseries, irregular, bar, stacked )

### ISSUE THREAD

**Issue by JiRadu** [apexcharts/apexcharts.js#1172]
## Codepen

https://codesandbox.io/s/problem-lnmh3?fontsize=14&hidenavigation=1&theme=dark

## Explanation

- What is the behavior you expect?
I was working on making a tooltip for the whole stacked bar ( I realize that the bug appears even if you comment on the tooltip part, but I felt like giving some context would help).
I expect to see all the users' bars displayed at all time
- What is happening instead?
They won't appear until I disabled (clicked on ) User 6. Only then they appear
- What error message are you getting?
None

Also: I only get that after I updated from:
apexcharts v3.6.5 to v3.11.0+ ( currently running 3.11.2 because 3.11.3 is throwing an error).

Also, the bars are overlapped not stacked (that is the reason why I updated in the first place)

**Comment by junedchhipa** [comment]
I can see that disabling User 6 in your example makes the bar appear again.
Weird issue, I will look into it.

Can you please also tell what error you're getting on 3.11.3?

**Comment by JiRadu** [comment]
Hi, I was getting 

>  i[this.chartType] is not a function

I can't reproduce anymore, it is now working on v3.11.3, but the bars are still overlapped as you can see in the demo :( 
Tremendous work for fixing that!

**Comment by JiRadu** [comment]
For more context:
The step in the timeseries is 1h, so when plotting, the values for 2 overlapped stacks are ( as far as i know ) exactly the same. However, if you look at 2 examples:
3 Dec, 19:00 -> two stacked bars are well placed
3 Dec, 21:00 -> the two stacked bars are overlapping

**Comment by junedchhipa** [comment]
Do the overlapping bars have the exact same "timestamp"?
Because the way I have coded is, the next stacked series searches for the same date in the previous series, and if it finds it, it stacks on top it.

If the same date is present in any other series, it should search for it too (which I think it doesn't currently).
If that is the case, please open a new issue with a new title (stacked bars overlaps)

**Comment by JiRadu** [comment]
I will open a new issue, sure.
The date is, to the best of my knowledge, exactly the same, the timestamp is trimmed by the hour so there are 5 zeros at the end of each timestamp.
